# services.yaml
cuckoo_clock:
  description: Play a cuckoo clock sound an x amount of times
  fields:
    entity_id:
      description: The light that will be turned on.
      example: media_player.living_room_speaker
    hour:
      description: The current hour, which will be used to calculate the amount of cuckoos
      example: 8
    minute:
      description: The current minute, which will be used to calculate the amount of cuckoos
      example: 0
