id: Half_hour
alias: Cuckoo Clock every 30 minutes
trigger:
  platform: time_pattern
  minutes: "/30"
condition:
  condition: time
  after: "06:31:00"
  before: "22:31:00"
action:
  service: script.cuckoo_clock
